### ISSUE TITLE
Add me to your friend list throws an internal error message

### ISSUE THREAD

**Issue by theRealImy** [solid/profile-pane#24]
Error displays as:
<img width="318" alt="grafik" src="https://user-images.githubusercontent.com/4144203/140720862-6d3a88f0-d761-4851-af15-914531fbcafe.png">
The console says:
Uncaught (in promise) Error: Fetcher: <https://timeatest.solidcommunity.net:8443/IndividualChats/timeatest.solidcommunity.net:8443/2021/11/> Not Found

**Comment by bourgeoa** [comment]
Why did you remove the error window. It is a great feature for user to know that the chat creation failed. The 500 is not nice, may be replaced by a better one.

Was it an ACL problem ?

**Comment by theRealImy** [comment]
The code was catching ALL uncaught errors from the displayed page. In this case, it was catching a chat error and displaying it under the Add me to your friend list button which is the wrong location for it anyway. 
I am not sure the user should know about an uncaught error in the code anyhow. It is enough if the dev knows and looks in the console.

**Comment by bourgeoa** [comment]
But the information was the chat was not created or is not working. Is this not of interest to the user ?

**Comment by theRealImy** [comment]
It might be of interest ... 
Do you agree that displaying it under the Add me to your friend button does bot tell the user that it is a chat issue actually?
If we want to display such errors we need to discuss a solution for them. However, that is not part of this code.

**Comment by bourgeoa** [comment]
The error is linked to the click on the button.

The concept and location is a good point for our brainstorming.

**Comment by theRealImy** [comment]
The error appears upon login for me. No need to click any button.
For the concept discussion, let's open a discussion or a new issue.

**Comment by theRealImy** [comment]
for further discussion see: https://github.com/solid/solidos/discussions/91
