### ISSUE TITLE
Hide empty friend list

### ISSUE THREAD

**Issue by angelo-v** [solid/profile-pane#4]
Hide friend list if there are no foaf:knows relations. In a later iteration we could do smarter things (like provide "add friend" button)

**Comment by RubenVerborgh** [comment]
Actually, might be clearer to say "no friends found", or people will wonder where the pane is.

**Comment by angelo-v** [comment]
Yes, you are right. In the first step I just wanted to keep track of what the current pane does. But it is probably reasonable to implement souch a message right away
